# Generated by Django 2.2.4 on 2021-08-18 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('commons', '0001_initial'), ('commons', '0002_comment_task'), ('commons', '0003_comment_updated_by'), ('commons', '0004_comment_created_by'), ('commons', '0005_comment_commented_on'), ('commons', '0006_auto_20210817_1858'), ('commons', '0007_comment_commented_on'), ('commons', '0008_auto_20210818_0838'), ('commons', '0009_remove_comment_status_time'), ('commons', '0010_comment_status_time')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0114_delete_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Предано')),
                ('status_task', models.CharField(blank=True, choices=[('в работе', 'В работе'), ('выполнена', 'Выполнена'), ('дополнительный контроль', 'Дополнительный контроль')], max_length=255, null=True, verbose_name='Статус заяки')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий к статусу')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_comments', to='tasks.Task')),
                ('updated_by', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Изменена')),
                ('created_by', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Создана')),
                ('commented_on', models.DateTimeField(auto_now_add=True, default='2020-08-26 18:30:52.045133+03', verbose_name='Created on')),
                ('status_time', models.DateTimeField(blank=True, null=True, verbose_name='Время исполнения')),
            ],
            options={
                'ordering': ['-commented_on'],
            },
        ),
    ]
