# Generated by Django 2.2.4 on 2021-08-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_squashed_0010_comment_status_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commented_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created on'),
        ),
    ]
