# Generated by Django 2.2.4 on 2021-08-18 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0006_auto_20210818_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_by',
        ),
    ]
