# Generated by Django 2.2.4 on 2021-10-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0007_remove_comment_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к статусу'),
        ),
    ]
