# Generated by Django 2.2.4 on 2022-01-27 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0008_auto_20211027_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-commented_on'], 'verbose_name': 'комментарий', 'verbose_name_plural': 'комментарии'},
        ),
    ]
