# Generated by Django 2.2.4 on 2021-07-07 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0108_auto_20210630_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('stop_time', models.DateTimeField(blank=True, null=True, verbose_name='Завершение')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('act', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='act_charts', to='tasks.Act')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_charts', to='tasks.Address')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_charts', to='tasks.Resource')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
