# Generated by Django 2.2.4 on 2021-07-07 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chart',
            options={},
        ),
        migrations.RemoveField(
            model_name='chart',
            name='act',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='address',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='description',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='stop_time',
        ),
    ]
