# Generated by Django 2.2.4 on 2021-07-07 12:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0108_auto_20210630_1428'),
        ('charts', '0002_auto_20210707_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chart',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='chart',
            name='act',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='act_charts', to='tasks.Act'),
        ),
        migrations.AddField(
            model_name='chart',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_charts', to='tasks.Address'),
        ),
        migrations.AddField(
            model_name='chart',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chart',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='chart',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_charts', to='tasks.Resource'),
        ),
        migrations.AddField(
            model_name='chart',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало'),
        ),
        migrations.AddField(
            model_name='chart',
            name='stop_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершение'),
        ),
    ]
