# Generated by Django 2.2.4 on 2021-07-07 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_auto_20210707_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='act',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.Act'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to='tasks.Address'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.Resource'),
        ),
    ]
