# Generated by Django 2.2.4 on 2021-08-18 10:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    replaces = [('tasks', '0001_initial'), ('tasks', '0002_auto_20200114_1310'), ('tasks', '0003_auto_20200114_1321'), ('tasks', '0004_auto_20200114_1340'), ('tasks', '0005_auto_20200114_1354'), ('tasks', '0006_auto_20200117_1503'), ('tasks', '0007_auto_20200120_1354'), ('tasks', '0008_auto_20200120_1358'), ('tasks', '0009_auto_20200120_1402'), ('tasks', '0010_auto_20200120_1545'), ('tasks', '0011_auto_20200301_2254'), ('tasks', '0012_auto_20200302_0216'), ('tasks', '0013_auto_20200302_0233'), ('tasks', '0014_task_source_task'), ('tasks', '0015_auto_20200302_0251'), ('tasks', '0016_auto_20200302_0349'), ('tasks', '0017_task_floor'), ('tasks', '0018_task_executor'), ('tasks', '0019_auto_20200303_1111'), ('tasks', '0020_task_transmission_time'), ('tasks', '0021_auto_20200303_1352'), ('tasks', '0022_auto_20200303_1357'), ('tasks', '0023_auto_20200304_1412'), ('tasks', '0024_auto_20200304_1412'), ('tasks', '0025_auto_20200304_1415'), ('tasks', '0026_auto_20200304_1417'), ('tasks', '0027_auto_20200304_1419'), ('tasks', '0028_auto_20200305_0851'), ('tasks', '0029_auto_20200305_0857'), ('tasks', '0030_auto_20200310_1146'), ('tasks', '0031_spradr'), ('tasks', '0032_auto_20200402_1647'), ('tasks', '0033_auto_20200410_1337'), ('tasks', '0034_auto_20200410_1403'), ('tasks', '0035_auto_20200410_1407'), ('tasks', '0036_auto_20200520_0939'), ('tasks', '0037_auto_20200604_1617'), ('tasks', '0038_task_status_time_2'), ('tasks', '0039_remove_task_status_time_2'), ('tasks', '0040_delete_spradr'), ('tasks', '0041_act_address_resource'), ('tasks', '0042_chart'), ('tasks', '0043_task_address'), ('tasks', '0044_auto_20201030_1431'), ('tasks', '0045_category'), ('tasks', '0046_auto_20201110_1549'), ('tasks', '0047_auto_20201111_0911'), ('tasks', '0048_auto_20201216_1638'), ('tasks', '0049_task_sms_is_active'), ('tasks', '0050_remove_task_sms_is_active'), ('tasks', '0051_task_sms_is_active'), ('tasks', '0052_task_sms_is_sended'), ('tasks', '0053_auto_20210408_1246'), ('tasks', '0054_remove_task_sms_is_active'), ('tasks', '0055_task_sms_is_active'), ('tasks', '0056_remove_task_phone'), ('tasks', '0057_task_phone'), ('tasks', '0058_remove_task_sms_is_sended'), ('tasks', '0059_remove_task_sms_is_active'), ('tasks', '0060_task_sms_is_active'), ('tasks', '0061_task_sms_is_sended'), ('tasks', '0062_task_sms_result'), ('tasks', '0063_auto_20210414_0905'), ('tasks', '0064_auto_20210414_0907'), ('tasks', '0065_remove_task_address_task'), ('tasks', '0066_auto_20210416_1344'), ('tasks', '0067_auto_20210419_1350'), ('tasks', '0068_auto_20210419_1415'), ('tasks', '0069_auto_20210419_1416'), ('tasks', '0070_auto_20210419_1430'), ('tasks', '0071_auto_20210419_1432'), ('tasks', '0072_auto_20210419_1436'), ('tasks', '0073_auto_20210419_1442'), ('tasks', '0074_auto_20210419_1448'), ('tasks', '0075_auto_20210419_1504'), ('tasks', '0076_auto_20210419_1514'), ('tasks', '0077_auto_20210419_1516'), ('tasks', '0078_auto_20210419_1550'), ('tasks', '0079_auto_20210419_1557'), ('tasks', '0080_auto_20210420_1525'), ('tasks', '0081_auto_20210421_1317'), ('tasks', '0082_auto_20210421_1321'), ('tasks', '0083_auto_20210421_1324'), ('tasks', '0084_auto_20210421_1326'), ('tasks', '0085_auto_20210421_1328'), ('tasks', '0086_auto_20210421_1336'), ('tasks', '0087_auto_20210421_1339'), ('tasks', '0088_auto_20210421_1348'), ('tasks', '0089_auto_20210421_1350'), ('tasks', '0090_auto_20210421_1351'), ('tasks', '0091_auto_20210421_1352'), ('tasks', '0092_auto_20210421_1355'), ('tasks', '0093_auto_20210421_1356'), ('tasks', '0094_auto_20210421_1358'), ('tasks', '0095_auto_20210421_1359'), ('tasks', '0096_auto_20210421_1401'), ('tasks', '0097_auto_20210421_1403'), ('tasks', '0098_auto_20210421_1435'), ('tasks', '0099_auto_20210421_1510'), ('tasks', '0100_task_sms_is_queue'), ('tasks', '0101_auto_20210427_0900'), ('tasks', '0102_auto_20210427_0901'), ('tasks', '0103_auto_20210520_1146'), ('tasks', '0104_auto_20210520_1151'), ('tasks', '0105_auto_20210629_0857'), ('tasks', '0106_auto_20210630_1421'), ('tasks', '0107_auto_20210630_1426'), ('tasks', '0108_auto_20210630_1428'), ('tasks', '0109_auto_20210707_1535'), ('tasks', '0110_auto_20210708_1003'), ('tasks', '0111_delete_chart'), ('tasks', '0112_auto_20210713_0853'), ('tasks', '0113_remove_task_history_status'), ('tasks', '0114_delete_status')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, unique=True, verbose_name='Действие')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, unique=True, verbose_name='Ресурс')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_subdivision', models.CharField(blank=True, max_length=64, unique=True, verbose_name='Подразделение')),
                ('is_active', models.BooleanField(blank=True, default=True)),
            ],
            options={
                'ordering': ('string_subdivision',),
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_address', models.CharField(blank=True, max_length=64, unique=True, verbose_name='Адрес')),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('string_subdivision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.Subdivision')),
            ],
            options={
                'ordering': ('string_address',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edsmo_id', models.PositiveSmallIntegerField(unique=True, verbose_name='Код в ЕДС')),
                ('visible', models.BooleanField(blank=True, default=True)),
                ('deadline', models.DurationField(blank=True, default=datetime.timedelta(0), null=True, verbose_name='Часов на исполнение')),
                ('name', models.CharField(blank=True, max_length=250, unique=True, verbose_name='Категория заявки')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('surname_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('status_task', models.CharField(blank=True, choices=[('в работе', 'В работе'), ('выполнена', 'Выполнена'), ('дополнительный контроль', 'Дополнительный контроль')], max_length=255, null=True, verbose_name='Статус заяки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Содержание заявки')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('patronymic_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('apartment', models.CharField(blank=True, max_length=55, null=True, verbose_name='Квартира')),
                ('porch', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Подъезд')),
                ('reu', models.CharField(blank=True, choices=[('РЭУ2-Москворецкий', 'РЭУ2-Москворецкий'), ('РЭУ3-Флотский', 'РЭУ3-Флотский'), ('РЭУ4-Окский', 'РЭУ4-Окский'), ('РЭУ5-Репинский', 'РЭУ5-Репинский'), ('РЭУ6-Колычевский', 'РЭУ6-Колычевский'), ('РЭУ8-Октябрьский', 'РЭУ8-Октябрьский'), ('РЭУ9-Заречный', 'РЭУ9-Заречный'), ('РЭУ10-Парковый', 'РЭУ10-Парковый'), ('РЭУ11-Центральный', 'РЭУ11-Центральный'), ('РЭУ12-Юбилейный', 'РЭУ12-Юбилейный'), ('Служба благоустройства', 'Служба благоустройства'), ('ЭМУ', 'ЭМУ'), ('Газовая служба', 'Газовая служба'), ('Мастер-лифт', 'Мастер-лифт'), ('Аварийная служба', 'Аварийная служба'), ('ВКХ Водоканал', 'ВКХ Водоканал'), ('ТК Тепло Коломны', 'ТК Тепло Коломны'), ('Электросеть', 'Электросеть')], max_length=255, null=True, verbose_name='РЭУ')),
                ('source_task', models.CharField(blank=True, choices=[('житель', 'Житель'), ('гжи', 'ГЖИ'), ('ук', 'УК'), ('администрация', 'Администрация'), ('Мастер-лифт', 'Мастер-лифт'), ('МУП "Тепло Коломны"', 'МУП "Тепло Коломны"'), ('интернет провайдер', 'Интернет провайдер')], max_length=255, null=True, verbose_name='Источник заявки')),
                ('floor', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('executor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Предано')),
                ('transmission_time', models.TimeField(blank=True, null=True, verbose_name='Время передачи')),
                ('comment_status', models.TextField(blank=True, null=True, verbose_name='Комментарий к статусу')),
                ('status_time', models.DateTimeField(blank=True, null=True, verbose_name='Время исполнения')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.Address')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.Category')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, verbose_name='Телефон')),
                ('sms_is_active', models.BooleanField(blank=True, default=False, verbose_name='Согласие на СМС')),
                ('sms_is_queue', models.BooleanField(blank=True, default=False, verbose_name='Смс уже в очереди')),
                ('sms_is_sended', models.BooleanField(blank=True, default=False, verbose_name='Смс отправлена')),
                ('sms_result', models.CharField(blank=True, max_length=55, null=True, verbose_name='Результат отправки')),
                ('created_by', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='Создана')),
                ('updated_by', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Изменена')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
