# Generated by Django 2.2.4 on 2022-01-27 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_profile_short_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='act',
            options={'ordering': ('name',), 'verbose_name': 'действие', 'verbose_name_plural': 'действия'},
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('string_address',), 'verbose_name': 'адрес', 'verbose_name_plural': 'адреса'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'профиль', 'verbose_name_plural': 'профиля'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ('name',), 'verbose_name': 'ресурс', 'verbose_name_plural': 'ресурсы'},
        ),
        migrations.AlterModelOptions(
            name='subdivision',
            options={'ordering': ('string_subdivision',), 'verbose_name': 'подразделение', 'verbose_name_plural': 'подразделения'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_on'], 'verbose_name': 'заявка', 'verbose_name_plural': 'заявки'},
        ),
    ]
